#keytool -genkey -alias ssldemo -dname "CN=Andy,OU=kfit,O=kfit,L=HaiDian,ST=BeiJing,C=CN"  -storetype PKCS12 -keyalg RSA -keysize 2048  -keystore keystore.p12 -validity 365  
#端口号
server:
  port: 80
#https:
    ##  port: 443
    ##  keystore-file:  keystore.p12
  ##  keystore-password:  adminLZJ123
  ##  keystore-type: PKCS12
#注册服务名称
#向eureka注册信息
eureka:
  client:
    service-url:
      #http://admin:admin123@localhost:6003/eureka
      defaultZone: http://eureka.didispace.com/eureka/
    #开启健康检查
    healthcheck:
        enabled: true
    #复制实例变化信息到eureka服务器所需要的时间间隔，默认单位为秒，默认时间为30秒
    instance-info-replication-interval-seconds: 10
  instance:
      #eureka注册中心在接收到实例的最后一次心跳后，需等待多久删除该实例，默认单位为秒，默认时间为90秒
      lease-expiration-duration-in-seconds: 10
      #该实例需多少秒向eureka注册中心发送心跳，以表明它仍然活着，默认单位为秒，默认时间为30秒
      lease-renewal-interval-in-seconds: 5
      metadata-map:
          my-metada: profZuul
      #以实例名称显示IP配置
      preferIpAddress: true
#设值ribbon超时时间
ribbon:
  ReadTimeout: 60000
  SocketTimeout: 60000
hystrix:
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 60000
            threadpool: 2
  default:
    coreSize: 50
    maximumSize: 10000
    allowMaximumSizeToDivergeFromCoreSize: true
    maxQueueSize: -1
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 30000000
#路由配置，每次修改一个微服务需要在里面进行对应的修改
logging:
  file: gateway.log
spring:
  application:
    name: profZuul
      #开启文件上传下载
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  redis:
    host: 127.0.0.1
    password: admin123
    database: 0
    timeout: 0
    port: 6379
#security:
#  oauth2:
#    client:
#      access-token-uri: http://localhost/auth/oauth/token
#      user-authorization-uri: http://localhost/auth/oauth/authorize
#      client-id: web
#    resource:
#      user-info-uri: http://localhost/auth/auth/member
#      prefer-token-info: false
zuul:
    #让每个网关都有一个自己的线程池，而不是共用一个线程池
      ribbon-isolation-strategy: thread
      thread-pool:
        use-separate-thread-pools: true
        thread-pool-key-prefix: zuulgw
      ssl-hostname-validation-enabled: false
      routes:
        auth:
          path: /auth/**
          service-id: profAuth
        web:
          #需要过滤的头信息
          sensitive-headers:
            Access-Control-Allow-Credentials,Access-Control-Allow-Origin,Access-Control-Expose-Headers,X-Frame-Options
          path: /**
          service-id: profWeb